version: '3.8'

services:
  app-dev:
    build: .
    container_name: nestjs-auth-dev
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:8
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 871804
      MYSQL_DATABASE: auth_db_dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

volumes:
  mysql_data_dev:
