version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-auth
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: nest
      DB_PASS: password
      DB_NAME: auth_example
    command: npm run start:prod

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nest123
      MYSQL_DATABASE: nest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
