version: '3.8'

services:
  app-prod:
    build: .
    container_name: nestjs-auth-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - mysql-prod

  mysql-prod:
    image: mysql:8
    container_name: mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_password
      MYSQL_DATABASE: auth_db_prod
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: Thunder.Devil123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql

volumes:
  mysql_data_prod:
